services:
    bots:
        build: .
        restart: unless-stopped
        env_file:
            - .env.prod
        networks:
            - multi-music-bots
        depends_on:
            lavalink:
                condition: service_healthy
            postgres:
                condition: service_healthy
        command: >
            sh - c "bun x prisma migrate deploy"

    redis:
        image: "redis:7.4.1"
        container_name: "redis-server"
        ports:
            - "6379:6379"
        environment:
            - REDIS_REPLICATION_MODE=master
        volumes:
            - redis-data:/data
            - ./redis.conf:/usr/local/etc/redis/redis.conf
        command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
        restart: always

    lavalink:
        image: ghcr.io/lavalink-devs/lavalink:4
        container_name: lavalink
        restart: unless-stopped
        environment:
            - _JAVA_OPTIONS=-Xmx6G
            - SERVER_PORT=2333
            - LAVALINK_SERVER_PASSWORD=youshallnotpass
        volumes:
            - ./application.yaml:/opt/Lavalink/application.yaml
            - ./plugins/:/opt/Lavalink/plugins/
        networks:
            - multi-music-bots
        expose:
            - 2333
        ports:
            - "2333:2333"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:2333/version"]
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 20s

    postgres:
        image: postgres:16
        container_name: postgres
        restart: unless-stopped
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=shiroko-multi-music-bot
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./users.acl:/usr/local/etc/redis/users.acl
        networks:
            - multi-music-bots
        ports:
            - "5433:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
            start_period: 10s

networks:
    multi-music-bots:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "172.25.0.0/16"
                  gateway: "172.25.0.1"
volumes:
    redis-data:
    postgres_data:
        driver: local
