version: "3.9"

services:
    bots:
        build: .
        restart: always
        env_file:
            - .env.prod
        networks:
            - multi-music-bots
        depends_on:
            - lavalink

    lavalink:
        image: ghcr.io/lavalink-devs/lavalink:4
        container_name: lavalink
        restart: unless-stopped
        environment:
            # set Java options here
            - _JAVA_OPTIONS=-Xmx6G
            # set lavalink server port
            - SERVER_PORT=2333
            # set password for lavalink
            - LAVALINK_SERVER_PASSWORD=youshallnotpass
        volumes:
            # mount application.yml from the same directory or use environment variables
            - ./application.yaml:/opt/Lavalink/application.yaml
            # persist plugins between restarts, make sure to set the correct permissions (user: 322, group: 322)
            - ./plugins/:/opt/Lavalink/plugins/
        networks:
            - multi-music-bots
        expose:
            # lavalink exposes port 2333 to connect to for other containers (this is for documentation purposes only)
            - 2333
        ports:
            # you only need this if you want to make your lavalink accessible from outside of containers
            - "2333:2333"

    # postgres:
    #     image: postgres:15
    #     container_name: postgres
    #     restart: unless-stopped
    #     environment:
    #         - POSTGRES_USER=myuser
    #         - POSTGRES_PASSWORD=mypassword
    #         - POSTGRES_DB=mydatabase
    #     volumes:
    #         - postgres_data:/var/lib/postgresql/data
    #     networks:
    #         - multi-music-bots
    #     ports:
    #         - "5433:5432"

networks:
    multi-music-bots:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "172.18.0.0/16"
                  gateway: "172.18.0.1"
# volumes:
#     postgres_data:
#         driver: local
